- name: install nginx and run
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package: #heterogenuos module that can run for all distri
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      
