# Note: rc 1 is return code, exit status

- name: check the user is or not other wise create user
  hosts: local
  connection: local
  become: yes
  tasks:

  - name: Check the user exist or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: True

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"

  - name: add user expense
    ansible.builtin.command: useradd expense
    when: USER.rc !=0

