- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:

  - name: install desire packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present

    loop:
    - nginx
    - mysql
    - postfix
    - httpd
