- name: use filters/fuctions
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      # if forgot course variable it will print Ansible defaultly 

     msg: "Hello {{ course | default ('Ansible') }}"

  - name: convert to  upper case
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to  lower case
    vars:
      goodmorning: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ goodmorning | upper }}"
