- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0bc41aa50c0fccefc
    sg_id: "sg-0b9fd6aabf64f5c40"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - fronted
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet: "{{ subnet_id }}"
      instant_type: "{{ t2.micro }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2-instances

  # Make sure that dependencies installed or not or else install it
  # pip3.9 install boto3 botocor
